<?xml version="1.0"?>
<definitions name="HemeraService"
 targetNamespace="http://169.254.3.230:8080/HemeraService"
 xmlns:tns="http://169.254.3.230:8080/HemeraService"
 xmlns:xsd="http://www.w3.org/2001/XMLSchema"
 xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
 xmlns="http://schemas.xmlsoap.org/wsdl/">

    <message name="proveRequest">
        <part name="formula" type="xsd:string"/>
    </message>
    <message name="proveResponse">
        <part name="return" type="xsd:string"/>
    </message>

    <portType name="HemeraPortType">
        <operation name="prove">
            <documentation> the prove method </documentation>
            <input message="tns:proveRequest"/>
            <output message="tns:proveResponse"/>
        </operation>
    </portType>

    <binding name="HemeraBinding" type="tns:HemeraPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="prove">
            <soap:operation soapAction="http://169.254.3.230:8080/HemeraService/prove"/>
            <input>
                <soap:body use="literal" namespace="http://169.254.3.230:8080/HemeraService"/>
            </input>
            <output>
                <soap:body use="literal" namespace="http://169.254.3.230:8080/HemeraService"/>
            </output>
        </operation>
    </binding>

    <service name="HemeraService">
        <documentation>Try to prove a theorem</documentation>
        <port name="HemeraPort" binding="tns:HemeraBinding">
            <soap:address location="http://169.254.3.230:8080/HemeraService"/>
        </port>
    </service>

</definitions>

